### ISSUE TITLE
Ubytování

### ISSUE THREAD

**Issue by rarous** [hackercampcz/donut#104]
Tabulka jako podklad: https://docs.google.com/spreadsheets/d/13QubMJE9Q0vPSylTCV59dYczRfKKrTDFthFaVHAMcmE/edit#gid=311217530

**Comment by junkycoder** [comment]
Máme v plánu na to s Radkem sednout v úterý (21. 6.) ráno. Připravíme návrh, pak začnu kódovat..

**Comment by rarous** [comment]
Tady je eště mapa areálu. Nevím jestli vám k něčemu bude, ale i tak :)
![image](https://user-images.githubusercontent.com/101581/174031926-364e89ef-523c-4e20-8e68-e584a1c58935.png)

**Comment by jaklradek** [comment]
Přidávám skeč co jsme si kreslili s @junkycoder během konzultace:
![rezervace_uidoodle_hackercamp](https://user-images.githubusercontent.com/8980849/174755503-2677a211-c974-422d-b670-80f282fef327.jpg)
.

**Comment by junkycoder** [comment]
Input s autocomplete https://autocomplete.trevoreyre.com/#/javascript-component

**Comment by rarous** [comment]
@junkycoder ale místo UL použij https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist.

EDIT: vlastně je to nativní a není potřeba JS vůbec :D

**Comment by junkycoder** [comment]
Nice a já koukám, že je to vcelku použitelný i na mobilu. Nebude tam teda dropdown, ale nad klávesnicí se ukazujou návrhy..

**Comment by junkycoder** [comment]
@rarous načtem všechný naráz, nebo vystavíme EP pro to našeptávání?

**Comment by rarous** [comment]
Můžeme zkusit oba, co bude lepší

**Comment by junkycoder** [comment]
1. načíst obsazenost objektů
	1. vygenerovat inputy
2. načíst hackery
	1. vygenerovat datalist
3. našeptávat jen neupíchnutý
5. zvýraznit tebe pokud jsi vyplněný
6. přidat mazátko k inputům co jsem vyplnil nebo sem já
7. nedovolit vyplnit nic než co je našeptáno
8. odeslat vyplněnou část datasetu na server -> dovolit obsadit jen neobsazeným a nebo tobě samotnýmu
9. přidat counter obsazenosti k objektu 
	1. collapsovat objekt když je plno (když tam nejsem já)
	2. collapsovat objekt vše kde nejsem já, pokud někde už jsem?



@rarous jen sem si tu rozepsal..

**Comment by junkycoder** [comment]
@rarous dataflow mam complete - https://donut.hackercamp.cz/ubytovani

Pro renderování objektů jsem si vytvořil několik [datasetů](https://github.com/hackercampcz/core/tree/trunk/donut.hackercamp.cz/src/static/housing) a jen ten `hackers.json" musí bejt na serveru ([teď je to mock](https://github.com/hackercampcz/core/blob/trunk/donut.hackercamp.cz/src/esm/housing.js#L9)).

Portrebuju už jen udělat nějaký tweaky v UX (collapsing sections, submit buttons, ..) a zablokovat některé roomy HC staffem.

**Comment by rarous** [comment]
Najs

**Comment by junkycoder** [comment]
Texty, ubytování (maily hlavně) https://docs.google.com/document/d/1wp9ES8_4XP50fGp5G4gPrkHdh8g2GFz9zhcg1P5mqPQ/
