### ISSUE TITLE
Aktualizace textu mailů

### ISSUE THREAD

**Issue by rarous** [hackercampcz/donut#188]
- [x] upravený text, co posílat všem, co se od zítřka zaregistrujou (obdoba toho, cos posílal dneska s urgencí na placení a slack. Odkazy je třeba zkontrolovat. 

https://docs.google.com/document/d/1fsCfeAbdynuG7FlWvokkdRkai-Uy5UlTf4XmEaxQVLo/edit#bookmark=id.77x5kmp5jkv5

- [x] Zde text pushe na hackery z 0, co se letos neozvali = loni byli na campu (máme jejich mail, nemusí být na slacku), ale letos ani registrace, ani opt-out. Může jít kdykoliv budeme ready.

https://docs.google.com/document/d/1_lzAsfWbxcbQ6KYGkkOxcGUb_GwHxbBU_-QIOuEj5LA/edit#bookmark=id.61bcrmepsvcv

- [x] Tady mail textu na účastníky = hackery 2022. Posílala bych po víkendu automatem,  hned jak doplníš tu FAQ k tomu přihlašování na slack.

https://docs.google.com/document/d/1_lzAsfWbxcbQ6KYGkkOxcGUb_GwHxbBU_-QIOuEj5LA/edit#bookmark=id.gzfbf6b72q9a

**Comment by irizatlouk** [comment]
- [x] tady první mail na waitinglistu: ale dej nám pár dní: https://docs.google.com/document/d/1fsCfeAbdynuG7FlWvokkdRkai-Uy5UlTf4XmEaxQVLo/edit#bookmark=kix.mn33jlc12hkr

- [x] tady druhý mail, co jim přijde, jak je v adminu z waitinglistu přesuneme do "potvrzených": https://docs.google.com/document/d/1fsCfeAbdynuG7FlWvokkdRkai-Uy5UlTf4XmEaxQVLo/edit#bookmark=kix.42iioyjhy98l
