### ISSUE TITLE
Reload of HTML 

### ISSUE THREAD

**Issue by junkycoder** [hackercampcz/donut#200]
```sh
➜ yarn start:donut.hackercamp.cz
```

Změna v `donut.hackercamp.cz/src/html/shared/hacker.njk` provede reload browser syncu, ale neprojeví se. Je nutný zabít dev a pustit znovu.

**Comment by junkycoder** [comment]
Možná to bude tím, že se profily hackerů generují zvlášť.

**Comment by rarous** [comment]
Ano, je to know limitation Blendidu. Tím jak je to generovaný z dat, to nejde úplně hooknout na watch. Když jsem to v minulosti zkoušel, docházelo k nekonečným cyklům. Většina profilu by stejně měla být generovaná klientsky. JS se na profilu reloaduje správně.
