### ISSUE TITLE
Public registration

### ISSUE THREAD

**Issue by rarous** [hackercampcz/donut#70]
# Registrace pro účastníky, kteří na HC ještě nebyli

* [x] Registrace je na adrese https://www.hackercamp.cz/registrace/ 
* [x] Registrace se odesílá na API endpoint https://api.hackercamp.cz/v1/registration jako `POST`, který přijímá FormData nebo JSON. Data musí mít vyplněné atributy `email` a `year`, které slouží jako klíče. Zbylá data se v DB uloží do sloupce typu Object. Není potřeba data nijak speciálně strukturovat.
* [x] Registrace umožňuje speciální odkazy pro `+1` lidí co byli loni (platí do 15. 6.) a pro lidi, co je pozval někdo z crew. (idea: použít ID Slack účtu jako referal, nebo hash emailu - horší párování). `GET` parametr `referral` se propíše do hidden pole formuláře.
* [x] Registrace umožní editaci. Pokud uživatel přijde přes odkaz s `?id=xxxx`, načtou se data z DB a můžou se upravit.

**Comment by junkycoder** [comment]
FYI @rarous, opravil jsem typo na `referral` a nahodil ho do formu 1c07d771d26ad741a994d23f67e63da05cd90c29

**Comment by junkycoder** [comment]
Public formulář konečně ukládá data, jen tě po odeslání nikam nenasměřuje

**Comment by rarous** [comment]
Yop, API zatím jen potvrdí uložení, nebo zařve chybou. Api by mělo vracet (na základě `Accept`) redirekt na HTML stránku s poděkováním a odkazem na editaci registrace, nebo JSON s linkem na editaci registrace.

**Comment by junkycoder** [comment]
Možná bych to teď s tim jásonem nekomplikoval. Stejnak máme jen jeden use-case (pro tento ročník)..

**Comment by rarous** [comment]
Přidat mail, který se pošle lidem ve waitinglistu, když nemají vyplněné fakturační údaje.
